### PR TITLE
Use new svd2rust 0.13

### PR DESCRIPTION
**Pull request by thejpster**
svd2rust 0.13 builds crates that compile on Rust Beta (which will the next stable).
I also used `form` to break down lib.rs into manageable pieces, as per https://docs.rs/svd2rust/0.13.0/svd2rust/#target--cortex-m and #6.

### CODE REVIEW

**Comment by whitequark** [comment]
1778 files? Is there perhaps a form option that limits how deep it's going to go? This is many enough files that I expect it to e.g. cause slowdown on Windows...

**Comment by Emilgardis** [comment]
> [...] a form option that limits how deep it's going to go?

This may be something to consider adding to form

cc @djmcgill

**Comment by djmcgill** [comment]
I would welcome a pull request, it would be a matter of adding an optional depth field to the Folder: https://github.com/djmcgill/form/blob/master/src/main.rs#L77, and a new CLI option to set it, and then decline to recurse if the depth is reached at https://github.com/djmcgill/form/blob/master/src/main.rs#L104. I think this is correct anyway, it's been a while.

I'm unlikely to work on it myself I'm afraid, at least any time soon.

**Comment by thejpster** [comment]
Even so, I think as it stands it's better than a 6 MiB `lib.rs` that you basically can't open or diff. 

On my Windows 10 laptop the time to `cargo check` went from 44 seconds to 48 seconds.

**Comment by whitequark** [comment]
How come you can't open it? Sublime Text does it without any issue over here.

**Comment by thejpster** [comment]
@whitequark could you push 0.7? I don't have push permissions on crates.io.

**Comment by whitequark** [comment]
I gave you push permissions.

**Comment by thejpster** [comment]
```
.../tm4c123x $ cargo publish
error: api errors: this crate exists but you don't seem to be an owner. If you believe this is a mistake, perhaps you need to accept an invitation to be an owner before publishing.
```

**Comment by whitequark** [comment]
You need to confirm yourself as an owner on the crates.io web interface.

**Comment by whitequark** [comment]
Also, I did push 0.7 yesterday. It seems to miss the `interrupt!` macro though.

**Comment by thejpster** [comment]
Huh. I do not recall seeing a notification about that. Thanks!

**Comment by thejpster** [comment]
interrupt! is behind the `rt` flag. Was that enabled?

**Comment by whitequark** [comment]
Ah, that was it. Thanks.

**Pull request merged**
